### ISSUE TITLE
how to generate the switch commands.txt

### ISSUE THREAD

**Issue by muyingluo1997** [ProbabilisticINT/Mininet-PINT#1]
You have provided the topology with 5 switches, and each switch was configured with file in "rules".Now, i want to expand the topology to 36, but i don't konw how the generate the commands.txt. Could you give me some tips?

**Comment by sivaramakrishnansr** [comment]
Hello! 

Have you tried to setup the experiment as follows:
`python topo_allocator.py 36`

`sudo python exp.py 36`

And to generate results: 
`python generate_results.py 36`

This would automatically generate the commands.txt. Do let me know if this helps.

**Comment by muyingluo1997** [comment]
yeah, it's helpful! thanks a lot
